GRANT EXECUTE ON PROCEDURE login TO role_login;
GRANT EXECUTE ON PROCEDURE user_registration TO role_login;
GRANT EXECUTE ON PROCEDURE fai_offerta TO role_user;
GRANT EXECUTE ON PROCEDURE stato_aste_utente TO role_user;
GRANT EXECUTE ON PROCEDURE imposta_controfferta TO role_user;
GRANT EXECUTE ON PROCEDURE visualizza_aste_passate TO role_user;
GRANT EXECUTE ON PROCEDURE visualizza_oggetti_asta TO role_user;
GRANT EXECUTE ON PROCEDURE indici_asta TO role_admin;
GRANT EXECUTE ON PROCEDURE inserisci_categoria TO role_admin;