GRANT EXECUTE ON PROCEDURE login TO role_login;
GRANT EXECUTE ON PROCEDURE user_registration TO role_login;
GRANT EXECUTE ON PROCEDURE make_offer TO role_user;
GRANT EXECUTE ON PROCEDURE user_auctions_informations TO role_user;
GRANT EXECUTE ON PROCEDURE set_counteroffer TO role_user;
GRANT EXECUTE ON PROCEDURE closed_auctions_informations TO role_user;
GRANT EXECUTE ON PROCEDURE auctions_in_progress_informations TO role_user;
GRANT EXECUTE ON PROCEDURE call_auction TO role_admin;
GRANT EXECUTE ON PROCEDURE insert_category TO role_admin;